# -*- coding: utf-8 -*-
"""PYTHONLAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XGeSp6yujHGYutn30Pads795M99JFR0P

2/02/2026 (Loops Concept)
"""

#print tables in range based on user input
n = int(input("Enter the no.of tables: "))
for i in range(1, n+1):
  print(f"Table {i}: ")
  for j in range(1, 11):
    print(i, "x", j, "=", i*j)

# print squares, cubes, prime present in range of n
n = int(input("Enter the value of n: "))
print(f"squares under {n}")
for i in range(1, n+1):
  if(i * i < n):
    print(i *i)
print(f"cubes under {n}")
for i in range(1, n +1):
  if(i * i * i < n):
    print(i * i * i)

#print the fibonacci series of range m if n = 1 and print tribonacci series of range m if n = 2
n = int(input("Enter the value of n(1 or 2): "))
if n == 1:
  m = int(input("Enter the range of Fibonacci series: "))
  print("Fibonacci series:")
  a, b = 0, 1
  for i in range(m):
      print(a, end=" ")
      a, b = b, a + b
  print()
elif n == 2:
  m = int(input("Enter the range of Tribonacci series: "))
  print("Tribonacci series:")
  t0, t1, t2 = 0, 1, 1

  if m >= 1:
    print(t0, end=" ")
  if m >= 2:
    print(t1, end=" ")
  if m >= 3:
    print(t2, end=" ")

  for _ in range(3, m):
    tn = t0 + t1 + t2
    print(tn, end=" ")
    t0, t1, t2 = t1, t2, tn
  print() # Add a newline for better formatting after the series
else:
  print("Invalid input")

#print prime factors of given range
n = int(input("Enter the range of n: "))
for i in range(2, n+1):

"""04/02/2026"""

#WRITE A PROGRAM IN PYTHON TO DEMONSTRATE THE CONCEPT OF STRINGS
a = 'hi'
b = "hi"
c = '''hi'''
print(type(a))
print(type(b))
print(type(c))
d = input("Enter a string: ")
print(d)
print(type(d))
e = "HELLO"
print(e[3])
print(e[0])
print(e[-3])

#write a string india and reverse it
str = "India"
print(str[-1:-6:-1])
print(str[::-1])
print(str[::])
print(str[:5:3])

"""09/02/2026"""

#doc string , lists = cplloection of items/elements, list allows to store all the datatypes, index - based,

l = [1, 1.23, "hello", False, 9+5j]
print(type(l[3]))
print(l)
l.append(99)
print(l)
l.pop()
print(l)
print(id(l))
print(type(l))
l[0] = 78
print(l)
print(l[0:5:2])

#Operators: it is a special symbol which is used to make operations on operands
#1. arthemetic operators: +,-,*,/(quotient),//(quotient but takes int value ex: 2.5 = 2), %(remainder), **
#relational(comparitive) operators: <,>,<=,>=, ==,!=
#assignment operators: =, +=, -=, *=, /=, %=
#logical operators: and, or, not
#bitwise operators: &, |, ^(XOR), ~(compliment), <<(left shift),>>(right shift), first operands will converted into binary, for compliment -(a+1), left shift: shift towards left, right shift: shift towards right
#unary minus operators
#membership operators: in, not in
#identity operators: is, is not, id

a,b = 10,20
print(a and b)
print(a or b)
print(not a)
print(not b)

a,b = 10, 20
print(a & b)
print(a | b)
print(a ^ b)
print(~a)
print(~b)
print(a << 2)
print(b >> 2)

#conditional statements: simple if, if-else, nested if, if-else-if
#if(condition):
#    #body
# when single condition exists

#if(condition):
#    #body
#else:
#    print()

age = int(input("Enter your age: "))
if age >= 18:
  print("eligible to vote")

#write a program in python to check whether the given number is +ve or -ve
n = int(input("Enter a number: "))
if n > 0:
  print("Positive number")
else:
  print("Negative number")

#wirte a program in python to check whether the given number is even or odd
n = int(input("Enter a number: "))
if n % 2 == 0:
  print("Even number")
else:
  print("Odd number")

#wirte a program in python to check whether the given char is vowel or consonent
vowels = ['a','e','i','o','u','A','E','I','O','U']
ch = input("Enter a character: ")
if ch in vowels:
  print("vowel")
else:
  print("consonent")

#wirte a program in python to check whether the given year is leap year or not
year = int(input("Enter a year: "))
if year % 4 == 0 and year % 100 != 0 or year % 400 == 0:
  print("leap year")
else:
  print("not a leap year")

#wirte a program in python to calculate the grade of a student with 5 subjects
sub1 = int(input("Enter marks of subject 1: "))
sub2 = int(input("Enter marks of subject 2: "))
sub3 = int(input("Enter marks of subject 3: "))
sub4 = int(input("Enter marks of subject 4: "))
sub5 = int(input("Enter marks of subject 5: "))
avg = (sub1 + sub2 + sub3 + sub4 + sub5) / 5
if avg >= 91 and avg <= 100:
  print("Grade A")
elif avg >= 71 and avg <= 90:
  print("Grade B")
elif avg >= 51 and avg <= 70:
  print("Grade C")
elif avg >= 35 and avg <= 50:
  print("Grade D")
else:
  print("Fail")

#wirte a program in python to calculate the electricity bill for first 100 units(3 rupees per unit), next 100 units(5 rupees per unit), above 200(7 rupees per unit)
units = int(input("Enter the number of units consumed: "))
if units <= 100:
  bill = units * 3
elif units >= 100 and units <= 200:
  bill = units* 3 + (units - 100) *5
else:
  bill = units * 3 + (units - 100) * 5 + (units - 200) * 7
print("total bill:", bill)

"""11/02/2026"""

#write a program in python to vaildate a triangle by using it's three sides
a = int(input("Enter the length of side 1: "))
b = int(input("Enter the length of side 2: "))
c = int(input("Enter the length of side 3: "))
if a == b == c:
  print("Equilateral triangle")
elif a == b or b == c or c == a:
  print("Isosceles triangle")
else:
  print("Scalene triangle")

#write a program in python of employee bonus calculation, if the employee service > 5 years 10% bonus, if salary < 50000 then again 5% bonus
experience = int(input("Enter the years of experience: "))
salary = int(input("Enter the salary: "))
if experience >= 5:
  bonus = salary + salary * 0.1
  if salary < 50000:
    bonus += salary * 0.05
  print("salary with bonus:", bonus)
else:
  print("No bonus")

#write a program in python for ATM withdraw simulation
input = int(input("Select a option(1 = deposit,2 = check balance,3 = withdraw)"))
deposit = int(input("Enter the amount to deposit: "))
balance = int(input("Enter the balance: "))
withdraw = int(input("Enter the amount to withdraw: "))
atm = int(input("Enter the ATM pin: "))
atm_pin = atm
if withdraw <= balance:
  balance -= withdraw
  print("Remaining balance:", balance)
else:
  print("Insufficient balance")

#Loops
#2 types of loops(pre test, post test)
#pre test has two types(for, while)
#post test has only on type(do-while)
#for loop: when having finite no.of iterations, index in for-loops is initiated by 'i'

#write a program in python to print first n natural numbers
n = int(input("Enter the value of n: "))
for i in range(1, n+1):
  print(i)

i = 1
while i<=10:
  print(i)
  i +=1

#write a python program to print even no's upto 50
for i in range(2, 51, 2):
  print(i)

#writw a python program to calculate the sum of digits until the single digit
num = int(input("Enter a number: "))
while num >= 10:
    sum_digits = 0
    while num > 0:
        sum_digits += num % 10
        num //= 10
    num = sum_digits

print("Single digit sum:", num)

#write a python program to check whether the given no is palindrom or not
num = int(input("Enter a number: "))
temp = num
rev = 0

while temp > 0:
    digit = temp % 10
    rev = rev * 10 + digit
    temp //= 10

if num == rev:
    print("Palindrome number")
else:
    print("Not a palindrome number")

#write a python program to check whether the given no is armstrong or not
num = int(input("Enter a number: "))
temp = num
digits = len(str(num))
total = 0

while temp > 0:
    digit = temp % 10
    total += digit ** digits
    temp //= 10

if num == total:
    print("Armstrong number")
else:
    print("Not an Armstrong number")

#write a program in pyton to print right-angled tringled
n = 4
for i in range(1, n + 1):
    for j in range(i):
        print("*", end=" ")
    print()

#write a program in python to print the square pattern
n = 4
for i in range(n):
    for j in range(n):
        print("*", end=" ")
    print()

#write a program in python to print the inversed right-angled triangle
n =4
for i in range(n, 0, -1):
    for j in range(i):
        print("*", end=" ")
    print()

#write a program in python to print the numbers in increasing order in right-angled triangle
n =4
for i in range(1, n + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()

#write a program in python to print floidstang
n = 5
num = 1

for i in range(1, n + 1):
    for j in range(i):
        print(num, end=" ")
        num += 1
    print()

#write a program in python to print pyramid
n = int(input("Enter number of rows: "))
for i in range(1, n + 1):
    for j in range(n - i):
        print(" ", end="")
    for k in range(2 * i - 1):
        print("*", end="")
    print()

"""25/02/26"""

#write a program to find the vowels in the given string using function
def count_vowels(s):
    vowels = "aeiouAEIOU"
    count = 0

    for ch in s:
        if ch in vowels:
            count += 1

    return count

# Main program
string = input("Enter a string: ")
result = count_vowels(string)

print("Number of vowels in the string:", result)

#write a function to check where given number is palindrome or not
s = input("Enter a string: ")
def is_palindrome(s):
  return s == s[::-1]
print(is_palindrome(s))

#write a function in python to check the factiorial of a number using iterators
s = int(input("enter a number: "))
def factorial(s):
  for i in range(1,s):
    s *= i
  return s
factorial(s)

n = int(input("Enter a number: "))
def factorial(n):
  res = 1
  for i in range(1, n+1):
    res *= i
  return res
factorial(n)

#write a function in python to print fibonacci series
n = int(input("Enter a number: "))
def fibonacci(n):
  a,b = 0,1
  for i in range(n):
    print(a, end = ' ')
    a,b = b, a+b
fibonacci(n)

# write a function to print the second largest number 11,22,33,44,55
n1 = [11,22,33,44,55]
def second_largest(n1):
  n1 = list(set(n1))
  n1.sort()
  return n1[-2]
second_largest(n1)









